### ISSUE TITLE
Error: __clone method called on non-object File: /src/pocketmine/command/Command Line: 333

### ISSUE THREAD

**Issue by ZizzyZizzy** [ServerSoftwareArchive/Tesseract#4]
#### Problem description
Error: __clone method called on non-object
File: /src/pocketmine/command/Command
Line: 333
Type: notice

#### Steps to reproduce the issue
Compile from source - build a0e2578 from 04-18-2017

#### OS and versions
* Tesseract: 1.2.1 RottenApple
* PHP: 7.0.15
* Server OS: CentOS 6.x
* Game version: 1.0.6
* Server host: self

#### Crashdump, backtrace, memory dumps, plugins list or other files
Code:
[324]    */
[325]   public function setUsage($usage){
[326]       $this->usageMessage = $usage;
[327]   }
[328]
[329]   public static final function generateDefaultData() : \stdClass{
[330]       if(self::$defaultDataTemplate === null){
[331]           self::$defaultDataTemplate = json_decode(file_get_contents(Server::getInstance()->getFilePath() . "src/pocketmine/resources/command_default.json"));
[332]       }
[333]       return clone self::$defaultDataTemplate;
[334]   }
[335]
[336]   /**
[337]    * @param CommandSender $source
[338]    * @param string        $message
[339]    * @param bool          $sendToSource
[340]    */
[341]   public static function broadcastCommandMessage(CommandSender $source, $message, $sendToSource = true){
[342]       if($message instanceof TextContainer){
[343]           $m = clone $message;

Backtrace:
#0 /src/pocketmine/command/defaults/VanillaCommand(32): pocketmine\command\Command->__construct(string weather, string %pocketmine.command.weather.description, string %pocke
tmine.command.weather.usage, array Array())
#1 /src/pocketmine/command/defaults/WeatherCommand(37): pocketmine\command\defaults\VanillaCommand->__construct(string weather, string %pocketmine.command.weather.descriptio
n, string %pocketmine.command.weather.usage)
#2 /src/pocketmine/command/SimpleCommandMap(108): pocketmine\command\defaults\WeatherCommand->__construct(string weather)
#3 /src/pocketmine/command/SimpleCommandMap(104): pocketmine\command\SimpleCommandMap->setDefaultCommands(boolean)
#4 /src/pocketmine/Server(1727): pocketmine\command\SimpleCommandMap->__construct(pocketmine\Server object)
#5 /src/pocketmine/PocketMine(468): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/multicraft/jar/pocketmine/
tesseract/1.0.6/Tesseract.phar/, string /home/multicraft/servers/server3/, string /home/multicraft/servers/server3/plugins/, string unknown)
#6 (9): include(string phar:///home/multicraft/jar/pocketmine/tesseract/1.0.6/Tesseract.phar/src/pocketmine/PocketMine.php)

**Comment by ZizzyZizzy** [comment]
Solved. **Someone nuked some files from the resources folder.** Copied them from an older source and it works fine now:

command_default.json
creativeitems.json
recipes.json

**Comment by NFGamerMC** [comment]
Please use this repo, the other one is illegal and will be tooken down soon!

**Comment by ZizzyZizzy** [comment]
That was from this repo. The other one is all kinds of broken.

**Comment by NFGamerMC** [comment]
Please re-install from this repo as your code name seems to be RottenApple, that is from the old one

**Comment by ZizzyZizzy** [comment]
DOH! I missed a source path in my build script. I was pulling from the old repo .zip file still.

Thanks.

**Comment by ZizzyZizzy** [comment]
Will leave this here for anyone else that grabs the wrong .zip file from the old repo...

Thanks and good luck with the fight to get the repo back. Freaking children that can't play nice with others, sheesh.

**Comment by NFGamerMC** [comment]
We are not children we are young 13-25 year olds. Also thanks for the issue report as we will still look into it!

**Comment by ZizzyZizzy** [comment]
Of course. I sincerely meant no offense to you.

I hope you are able to work things out and put things back in order and back in the spirit of GitHub.

**Comment by TheRoyalBlock** [comment]
We will work things out, but we have a few github support issues.

**Comment by NFGamerMC** [comment]
@TheRoyalBlock Please tell me if you are in that age range, we can have anyone under 12 as it is bad for our rep.

**Comment by TheRoyalBlock** [comment]
I am 13.

**Comment by NFGamerMC** [comment]
Okay, wanted to make sure you weren't 9, I can see that turning into a disaster. Lolz

**Comment by NFGamerMC** [comment]
@ZizzyZizzy That is okay
