### ISSUE TITLE
Please take this down

### ISSUE THREAD

**Issue by archie426** [ServerSoftwareArchive/Tesseract#6]
Ok first of all, sorry for not using the format, there is literally no point doing it like that.
Will someone give me a reason that this is better than PocketMine/PMMP? 
I would like to do this in a nice and calm and civilised manner (which I know is hard for some of you)
Please can this be taken down.
If you want to help you can contribute to PMMP at the main repo by FORKING (not spooning) and pull requesting.
If you are obsessed with taking all the credit for the project, when all that you have done is copy code, just create your own with no code stolen from other projects. If you have done that much to make this into a great server software (just stating what you think), why not create one from scratch
Your time in reading this is greatly appreciated

**Comment by NFGamerMC** [comment]
Thank You, but you may not have known this but pmmp is a fork of Pocketmine! We do this to create a stable server software. This repo will not be coming down as I believe that people should have a choice.

**Comment by LordJoshie** [comment]
@archie426 Tesseract has more/ is more stable & doesn't need API compatibility for plugins.... 

It's better for many reasons, those are a couple. 

more active devs, and most of PMMP code now is borrowed from other forks... many different projects based off the same idea all share their work. not everyone is able to work on the same project easily, so they work independently knowing their work can be taken by someone else for their own use. 

if PMMP wanted it's shit kept private, it wouldn't be posted to a free account on an open source website.

**Comment by MCPEGamerJPatGitHub** [comment]
@archie426 Many people prefer using Tesseract over pmmp. Main reason for that is it has more compatibility for older plugins (for those who can't code) and it is based on features rather than system.
I have no idea what @dktapps is trying to do, I feel like pmmp is all over the place now, not trying to achieve anything without being a software for non-production servers.

**Comment by NFGamerMC** [comment]
@MCPEGamerJPatGitHub Yes, I feel the same way. But I do believe in Bug Fixes also.

**Comment by AppleDevelops** [comment]
Think, when you make this issue, is it helping you in any way? Do you think we're gonna say, "Damn he's right, let's delete this work." No we're going to continue this whether you care or not, I don't give a damn what you or the PMMP members say, we aren't shutting down.

**Comment by NFGamerMC** [comment]
Yes!

**Comment by archie426** [comment]
Well, then, if Tesseract is so good. Then the devs must be really good. Lets see how they do at making their own server software without using any other code from other projects. PMMP is the most stable, fastest and well developed PHP, MCPE server software. I thought some people would be able to understand what I mean here, but obviously not

**Comment by MCPEGamerJPatGitHub** [comment]
@archie426 Your words mean nothing to us. We will continue to do what we are doing.

**Comment by AppleDevelops** [comment]
I suggest that you don't poke your way up the wrong alley

**Comment by HimbeersaftLP** [comment]
But why don't you make use of that "fork" button in the top-right corner of the PocketMine Repo? Does that hurt so much?

**Comment by NFGamerMC** [comment]
Poke, Poke. Lol

**Comment by archie426** [comment]
@AppleDevelops Yes quite, except you seem to attract people who need a good server software to the wrong alley, don't you. Oh yes, because Tesseract is SOOO stable.
@MCPEGamerJPatGitHub Typical noob talk. UR WORDSFHFH MESNFHHFAN NOTHINHG TO US I CRI

**Comment by AppleDevelops** [comment]
Go back to dickriding Dylan, the PMMP repo he has created himself is a spoon of the original PM.

**Comment by AppleDevelops** [comment]
Keep dickriding, it gets you no where in life

**Comment by NFGamerMC** [comment]
True. If you don't like this then you can bother Dylan, or the people on the forums!

**Comment by daniktheboss** [comment]
I came late. But pmmp the only thing I hate it, 1. Plugins break 24/7, alpha-shit-what-to-do-next, and the fact that they think everyone should start using pmmp. Pmmp isn't the shit! There will be forks no matter what! Stop telling everyone to use pmmp!
