### ISSUE TITLE
You gave me no other choice

### ISSUE THREAD

**Issue by archie426** [ServerSoftwareArchive/Tesseract#8]
I wanted to do this in a civilised manner, you obviously did not. Duplicate issue, if this is closed then I will make another one
So don't blame me for this....
Ok first of all, sorry for not using the format, there is literally no point doing it like that.
Will someone give me a reason that this is better than PocketMine/PMMP?
I would like to do this in a nice and calm and civilised manner (which I know is hard for some of you)
Please can this be taken down.
If you want to help you can contribute to PMMP at the main repo by FORKING (not spooning) and pull requesting.
If you are obsessed with taking all the credit for the project, when all that you have done is copy code, just create your own with no code stolen from other projects. If you have done that much to make this into a great server software (just stating what you think), why not create one from scratch
Your time in reading this is greatly appreciated

**Comment by NFGamerMC** [comment]
Banned!

**Comment by archie426** [comment]
Like I said, you obviously dont like to be civilised

**Comment by NFGamerMC** [comment]
I would (don't know about Apple), you can't make spam. That will get your account disabled!

**Comment by NFGamerMC** [comment]
Asking someone to delete a years work is unacceptable!
